apiVersion: v1
kind: Service
metadata:
  name: 'openresty-7.4'
  namespace: default
spec:
  ports:
  - name: openresty
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: 'k8s-openresty-php-7.4'
  sessionAffinity: None
  type: NodePort