apiVersion: v1
kind: Service
metadata:
  name: 'nginx'
  namespace: default
spec:
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: 'k8s-openresty-php'
  sessionAffinity: None
  type: NodePort